### ISSUE TITLE
Branching Strategy and prep for 1.0.x releases

### ISSUE THREAD

**Issue by handavid** [cloudera/director-google-plugin#117]
I was wondering what the branching strategy is on the director-google-plugin repo. I see that there are v1.0 and a release-1.0.1 branch. When we released Director 2.0, I tagged the repo with the release-1.0.1 and cloudera-director-2.0 tags to match the previous releases. It seems to me that the v1.0 branch is probably old and the release-1.0.1 branch can be renamed and repurposed to development-1.0.x or similar.

I want to create the development branch so that we can backport  https://github.com/cloudera/director-google-plugin/commit/3846079eb4f6a6e1563fcce2a59b9821716b6afe and in preparation for a 1.0.2 release of the plugin. As it stands, instances spun up by the 1.0.1 plugin using the rhel6 image alias will fail to complete bootstrapping due to yum issues.

I wanted to make sure that the branching strategy works for everyone before making these changes.

**Comment by duftler** [comment]
I think this sounds fine.

So the end result will be the stale v1.0 branch will be deleted, and the
release-1.0.1 branch will have the rhel and centos commits cherry-picked on
top? It will then become a new development-release-1.0.2 branch and tagged
with release-1.0.2 when it is released?

**Comment by handavid** [comment]
Matt,

That's what I had in mind with one change. Rather than development-release-1.0.2, I propose just calling it development-1.0 so that it can be reused for 1.0.x patch releases. We can tag it release-1.0.2 when that goes out and version bump the development branch in in preparation for 1.0.3 and future 1.0.x releases.

David

**Comment by duftler** [comment]
Sounds good to me.

**Comment by handavid** [comment]
great. I'll update the branches, version bump to 1.0.2-SNAPSHOT, and cherry-pick the commits to close this issue.

**Comment by duftler** [comment]
Thanks David.
